export const BEFORE_SECS = [
  {
    id: "resume",
    ico: "✅",
    bg: "#f3f4f6",
    nm: "Résumé du dossier — Liste rapide des documents",
    badge: { t: "À consulter d'abord", c: "b-blu" },
    note: {
      t: "Vue d'ensemble simplifiée. Cochez chaque document au fur et à mesure. Pour les détails (comment obtenir, traduction, etc.), consultez les sections ci-dessous.",
      c: "n-grn",
    },
    items: [
      // Campus France
      {
        id: "r-cf1",
        t: "Message de fin de procédure Campus France",
        d: "🖨️ Couleur ×1 + N&B ×1",
        s: "",
        g: ["req"],
        linkedTo: "cf1",
      },
      {
        id: "r-cf2",
        t: "Attestation de préinscription M2",
        d: "🖨️ Couleur ×1 + N&B ×1",
        s: "",
        g: ["req"],
        linkedTo: "cf2",
      },
      {
        id: "r-cf3",
        t: "Formulaire France-Visas (signé × 2)",
        d: "🖨️ Couleur ×2 — signer les 2 à la main",
        s: "",
        g: ["req"],
        linkedTo: "cf3",
      },
      // Diplômes
      {
        id: "r-dip1",
        t: "Diplôme original",
        d: "📄 Original physique + copies certifiées N&B",
        s: "",
        g: ["req"],
        linkedTo: "dip1",
      },
      {
        id: "r-dip2",
        t: "Baccalauréat original",
        d: "📄 Original physique + copies certifiées N&B",
        s: "",
        g: ["req"],
        linkedTo: "dip2",
      },
      {
        id: "r-dip3",
        t: "Relevés de notes (L1–M2)",
        d: "📄 Originaux papier + photocopies N&B",
        s: "",
        g: ["req"],
        linkedTo: "dip3",
      },
      // Identité & Civil
      {
        id: "r-civ1",
        t: "Passeport en cours de validité",
        d: "📄 Original + 2 jeux de photocopies N&B",
        s: "",
        g: ["req"],
        linkedTo: "civ1",
      },
      {
        id: "r-civ2",
        t: "2 photos d'identité OACI",
        d: "📸 Photos papier studio — 35×45 mm fond blanc",
        s: "",
        g: ["req"],
        linkedTo: "civ2",
      },
      {
        id: "r-civ3",
        t: "Acte de naissance avec filiation",
        d: "📄 Original + copie N&B (+ traduction si arabe)",
        s: "",
        g: ["req"],
        linkedTo: "civ3",
      },
      {
        id: "r-civ4",
        t: "Fiche familiale d'état civil",
        d: "📄 Original + copie N&B",
        s: "",
        g: ["req"],
        linkedTo: "civ4",
      },
      // Ressources financières
      {
        id: "r-fin1",
        t: "Attestation de travail (employeur)",
        d: "📄 Original papier en-tête + copie N&B",
        s: "",
        g: ["req"],
        linkedTo: "fin1",
      },
      {
        id: "r-fin2",
        t: "Bulletins de salaire (1–2 mois)",
        d: "📄 Originaux papier + photocopies N&B",
        s: "",
        g: ["req"],
        linkedTo: "fin2",
      },
      {
        id: "r-fin3",
        t: "Relevés CCP (1–2 mois)",
        d: "📄 Original poste ou 🖨️ Couleur ×1 + N&B ×1 si BaridiWeb",
        s: "",
        g: ["req"],
        linkedTo: "fin3",
      },
      {
        id: "r-fin4",
        t: "CV complet en français",
        d: "🖨️ N&B ×1 seulement",
        s: "",
        g: ["req"],
        linkedTo: "fin4",
      },
      {
        id: "r-fin5",
        t: "Capture exonération partielle CVEC",
        d: "🖨️ Couleur ×1 + N&B ×1 — capture d'écran du portail CVEC",
        s: "",
        g: ["req"],
        linkedTo: "fin5",
      },
      // Garant France
      {
        id: "r-gf1",
        t: "Attestation de prise en charge belle-sœur (légalisée)",
        d: "📄 Original légalisé mairie Paris + copie N&B",
        s: "",
        g: ["req"],
        linkedTo: "gf1",
      },
      {
        id: "r-gf2",
        t: "3 bulletins de salaire belle-sœur",
        d: "🖨️ Couleur ×1 + N&B ×1 — PDFs WhatsApp",
        s: "",
        g: ["req"],
        linkedTo: "gf2",
      },
      {
        id: "r-gf3",
        t: "3 relevés bancaires belle-sœur",
        d: "🖨️ Couleur ×1 + N&B ×1 — PDFs WhatsApp",
        s: "",
        g: ["req"],
        linkedTo: "gf3",
      },
      {
        id: "r-gf4",
        t: "Pièce d'identité belle-sœur (recto-verso)",
        d: "🖨️ Couleur ×1 + N&B ×1 — scan WhatsApp",
        s: "",
        g: ["req"],
        linkedTo: "gf4",
      },
      {
        id: "r-gf5",
        t: "Justificatif domicile belle-sœur (< 3 mois)",
        d: "🖨️ Couleur ×1 + N&B ×1 — PDF WhatsApp",
        s: "",
        g: ["req"],
        linkedTo: "gf5",
      },
      {
        id: "r-gf6",
        t: "Avis d'imposition belle-sœur 2024",
        d: "🖨️ Couleur ×1 + N&B ×1 — PDF impots.gouv.fr",
        s: "",
        g: ["req"],
        linkedTo: "gf6",
      },
      {
        id: "r-gf9",
        t: "Compte épargne belle-sœur",
        d: "🖨️ Couleur ×1 + N&B ×1 — PDF WhatsApp",
        s: "",
        g: ["req"],
        linkedTo: "gf9",
      },
      {
        id: "r-gf7",
        t: "Acte de mariage du frère",
        d: "📄 Original + copie N&B (+ traduction si arabe)",
        s: "",
        g: ["req"],
        linkedTo: "gf8",
      },
      // Garant Algérie
      {
        id: "r-gd1",
        t: "Attestation prise en charge parent (légalisée APC)",
        d: "📄 Original légalisé APC + copie N&B",
        s: "",
        g: ["opt"],
        linkedTo: "gd1",
      },
      {
        id: "r-gd2",
        t: "Attestation pension retraite parent (CNAS/CNR)",
        d: "📄 Original papier + copie N&B",
        s: "",
        g: ["opt"],
        linkedTo: "gd2",
      },
      {
        id: "r-gd3",
        t: "Relevés CCP parent (3 mois)",
        d: "📄 Original poste ou 🖨️ Couleur ×1 + N&B ×1 si BaridiWeb",
        s: "",
        g: ["opt"],
        linkedTo: "gd3",
      },
      {
        id: "r-gd4",
        t: "Attestation d'affiliation CNAS du parent",
        d: "📄 Original papier CNAS + copie N&B",
        s: "",
        g: ["opt"],
        linkedTo: "gd4",
      },
      {
        id: "r-gd5",
        t: "CNI du parent retraité",
        d: "📄 Original + copie N&B recto-verso",
        s: "",
        g: ["opt"],
        linkedTo: "gd5",
      },
      // Hébergement
      {
        id: "r-lgt1",
        t: "Confirmation réservation hôtel Besançon (Agoda)",
        d: "🖨️ Couleur ×1 + N&B ×1 — PDF email Agoda",
        s: "",
        g: ["req"],
        linkedTo: "lgt1",
      },
      {
        id: "r-lgt2",
        t: "Itinéraire Google Maps (hôtel ↔ université)",
        d: "🖨️ N&B ×1 — capture d'écran ou PDF",
        s: "",
        g: ["req"],
        linkedTo: "lgt2",
      },
      // Lettres
      {
        id: "r-let1",
        t: "Lettre de motivation",
        d: "🖨️ N&B ×1 — rédigée par toi",
        s: "",
        g: ["req"],
        linkedTo: "let1",
      },
      {
        id: "r-let2",
        t: "Lettre d'hébergement",
        d: "🖨️ N&B ×1 — rédigée par toi",
        s: "",
        g: ["req"],
        linkedTo: "let2",
      },
      {
        id: "r-let3",
        t: "Lettre ressources financières",
        d: "🖨️ N&B ×1 — rédigée par toi",
        s: "",
        g: ["req"],
        linkedTo: "let3",
      },
      {
        id: "r-let4",
        t: "Lettre d'engagement du père",
        d: "🖨️ N&B ×1 — rédigée par le père",
        s: "",
        g: ["req"],
        linkedTo: "let4",
      },
      {
        id: "r-let5",
        t: "Lettre prise en charge belle-sœur",
        d: "📄 Original légalisé mairie Paris + copie N&B",
        s: "",
        g: ["req"],
        linkedTo: "let5",
      },
      {
        id: "r-let6",
        t: "Lettre lien de parenté — père",
        d: "🖨️ N&B ×1 — rédigée par toi",
        s: "",
        g: ["req"],
        linkedTo: "let6",
      },
      {
        id: "r-let7",
        t: "Lettre lien de parenté — belle-sœur",
        d: "🖨️ N&B ×1 — rédigée par toi",
        s: "",
        g: ["req"],
        linkedTo: "let7",
      },
      // Documents additionnels
      {
        id: "r-extra1",
        t: "Lettre explicative personnelle",
        d: "🖨️ N&B ×1 — document que tu rédiges toi-même",
        s: "",
        g: ["req"],
        linkedTo: "rdv1",
      },
    ],
  },
  {
    id: "terms",
    ico: "📖",
    bg: "#fffbeb",
    nm: "Définitions essentielles — Lire en premier",
    badge: { t: "Lire d'abord", c: "b-amb" },
    note: {
      t: "Ces termes sont souvent confondus. Les comprendre évite des erreurs graves dans la préparation du dossier.",
      c: "n-blu",
    },
    expls: [
      {
        t: "Bulletin de salaire vs Relevé de compte vs Avis d'imposition",
        b: `<b>Bulletin de salaire (fiche de paie) :</b> Document mensuel émis par ton <em>employeur</em>. Montre ton salaire brut, net, les cotisations. Prouve que tu travailles et combien tu gagnes.<br><br>
<b>Relevé de compte (extrait bancaire) :</b> Document mensuel émis par ta <em>banque</em> (ou Algérie Poste pour le CCP). Montre les mouvements réels d'argent — virements reçus, dépenses. Prouve que l'argent du bulletin a bien été versé sur ton compte. Les deux doivent être cohérents.<br><br>
<b>Avis d'imposition :</b> Document annuel émis par l'administration <em>fiscale française</em>. Récapitule les revenus déclarés l'année précédente. Le consulat l'exige pour le garant (belle-sœur) pour confirmer ses revenus sur impots.gouv.fr. En Algérie, cela n'existe pas de la même façon — remplacé par l'attestation de pension pour les retraités.`,
      },
      {
        t: "Copie certifiée conforme — comment l'obtenir en Algérie",
        b: `<b>C'est quoi :</b> C'est une photocopie d'un document original sur laquelle un agent officiel appose un cachet + signature pour certifier que "la copie est conforme à l'original". Elle a valeur légale.<br><br>
<b>OÙ LA FAIRE :</b><br>
→ <b>APC (mairie) de ta commune :</b> service "légalisation". Tu apportes l'original + une photocopie claire. L'agent compare, appose tampon + signature. Coût : gratuit ou timbre de 20–50 DA.<br>
→ <b>L'université émettrice (pour les diplômes) :</b> encore mieux. La copie certifiée par l'établissement qui a délivré le document a plus de poids. Demande au bureau du doyen (cachet université + signature).<br><br>
<b>IMPORTANT :</b> Le ministère n'est PAS requis pour les documents destinés à la France. La certification APC ou université suffit pour le consulat.`,
      },
      {
        t: "Traduction assermentée — qui la fait, pas la mairie",
        b: `<b>C'est quoi :</b> Une traduction réalisée par un traducteur officiel agréé par un tribunal. Elle a valeur légale. La traduction Google ou par un ami ne suffit PAS.<br><br>
<b>LA MAIRIE NE TRADUIT PAS :</b> L'APC certifie les copies. Elle ne traduit pas. Ce sont deux choses différentes.<br><br>
<b>OÙ TROUVER UN TRADUCTEUR ASSERMENTÉ :</b><br>
→ Barreau des avocats de ta wilaya → liste des experts judiciaires agréés<br>
→ Centres de traduction agréés à M'Sila, Constantine, Alger<br>
→ Annuaires en ligne : chercher "traducteur assermenté arabe-français Algérie"<br><br>
<b>Prix :</b> 1 000 – 3 000 DA par document selon la longueur.<br>
<b>Délai :</b> 24h à 5 jours.<br>
<b>Documents à traduire si en arabe :</b> acte de naissance, relevés de notes.`,
      },
    ],
    items: [],
  },
  {
    id: "cf",
    ico: "🎓",
    bg: "#eff6ff",
    nm: "Campus France — Documents officiels",
    badge: { t: "Obligatoire", c: "b-red" },
    note: {
      t: "<strong>Après ton RDV de vérification mercredi</strong>, le message de fin de procédure est généré automatiquement par Campus France et envoyé par email. SANS ce message, ton dossier visa est incomplet.",
      c: "n-blu",
    },
    chain: true,
    items: [
      {
        id: "cf1",
        t: "Message de fin de procédure Campus France",
        d: "Email automatique Campus France après validation de l'authentification. C'est le sésame du visa.",
        s: '<b>1. Attendu après mercredi</b> (RDV vérification diplômes).<br><b>2. Vérifier</b> sur ton compte <a href="https://etudes-en-france.fr" target="_blank">etudes-en-france.fr</a> → "Mon dossier" → télécharger l\'attestation.<br><b>3. Imprimer</b> en 2 exemplaires propres. Mettre en première position dans le classeur.',
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDF numérique. CAPAGO garde le N&B, tu gardes le couleur.",
        g: ["req", "Après mercredi"],
      },
      {
        id: "cf2",
        t: "Attestation de préinscription / admission M2",
        d: "Document officiel de l'Université Marie et Louis Pasteur confirmant ton inscription au M2 Systèmes Logiciels.",
        s: "<b>Où :</b> compte etudes-en-france.fr → espace établissement → télécharger attestation.<br><b>Si pas disponible :</b> email à la scolarité → scolarite-sciences[at]univ-fcomte.fr avec ton nom et numéro de dossier.",
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDF numérique. CAPAGO garde le N&B, tu gardes le couleur.",
        g: ["req"],
      },
      {
        id: "cf3",
        t: "Formulaire France-Visas — rempli, imprimé, signé ×2",
        d: "Formulaire officiel de demande de visa long séjour. DOIT être signé à la main avec stylo noir.",
        s: '<b>1. Aller sur :</b> <a href="https://france-visas.gouv.fr" target="_blank">france-visas.gouv.fr</a><br><b>2. Naviguer :</b> "J\'ai besoin d\'un visa" → Long séjour → Étudiant → Algérie<br><b>3. Remplir</b> toutes les rubriques en FRANÇAIS. Adresse hébergement = adresse hôtel Besançon.<br><b>4. Imprimer</b> en 2 exemplaires.<br><b>5. Signer</b> à la main — PAS de signature numérique.',
        print: "🖨️ COULEUR ×2 — Les 2 exemplaires doivent être signés à la main. CAPAGO garde les 2. PAS de N&B pour ce document.",
        g: ["req"],
      },
    ],
  },
  {
    id: "dip",
    ico: "📜",
    bg: "#fffbeb",
    nm: "Diplômes & Relevés de notes",
    badge: { t: "Récupérer dimanche", c: "b-amb" },
    note: {
      t: "<b>Diplôme définitif :</b> tu l'as. Campus France a authentifié ton diplôme original. Tu le récupères dimanche. Le provisoire est pour ceux qui n'ont pas encore le définitif — pas ton cas. <b>MAE Constantine :</b> NON obligatoire pour le visa France (exemption art. 36, protocole franco-algérien 1962).",
      c: "n-grn",
    },
    chain: true,
    items: [
      {
        id: "dip1",
        t: "Diplôme universitaire original — récupérer dimanche + copies certifiées",
        d: "Campus France a authentifié ton diplôme original. À récupérer ce dimanche.",
        s: "<b>Dimanche :</b> Récupérer l'original physique.<br><b>Ensuite immédiatement :</b> Faire 3 copies certifiées conformes. <b>Où ?</b> Directement au bureau du doyen de ton université → apporter original + 3 feuilles photocopiées → demander \"certification conforme à l'original\" avec cachet université + signature.<br><b>Stocker :</b> original dans une pochette plastique rigide. Copies dans le classeur.",
        print: "📄 ORIGINAL physique + copies certifiées N&B. Ne jamais donner l'original.",
        g: ["req", "Dimanche"],
      },
      {
        id: "dip2",
        t: "Bac original — déjà récupéré ✓",
        d: "Valide et en ta possession. À conserver précieusement.",
        s: "<b>Action :</b> photocopier 3 fois. Porter les copies + l'original à l'APC → service légalisation → tampon + signature. Timbre 20–50 DA.<br><b>Ne jamais donner l'original seul.</b>",
        print: "📄 ORIGINAL physique + copies certifiées N&B. Pas d'impression couleur nécessaire.",
        g: ["don"],
      },
      {
        id: "dip3",
        t: "Relevés de notes — toutes les années universitaires",
        d: "De la L1 (1ère année) jusqu'au dernier diplôme. Chaque année doit figurer.",
        s: '<b>Où obtenir :</b> Service de scolarité de ton université → demander "relevés de notes officiels" pour chaque année académique.<br><b>Si en arabe :</b> traduction assermentée arabe→français.<br><b>Copies :</b> certifier à l\'université — 1 originale certifiée + 1 copie par document.',
        print: "📄 ORIGINAUX papier + photocopies N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "dip4",
        t: "MAE Constantine — optionnel / après visa seulement",
        d: "PAS obligatoire pour le visa France. Utile si l'université de Besançon l'exige à l'inscription physique.",
        s: "<b>Pour le visa :</b> exemption franco-algérienne (art. 36, accord 1962) → tu n'en as PAS besoin.<br><b>Si l'université le demande à l'inscription :</b> annexe régionale MAE à Constantine, ou par courrier via service T@SDIK. Timbre fiscal 20 DA par document.",
        g: ["opt", "Après visa"],
      },
    ],
  },
  {
    id: "civ",
    ico: "🪪",
    bg: "#f0fdf4",
    nm: "Identité & Documents civils",
    badge: { t: "À préparer", c: "b-amb" },
    items: [
      {
        id: "civ1",
        t: "Passeport en cours de validité — original + 2 jeux de photocopies",
        d: "Validité min. = date fin de séjour prévu + 3 mois. Doit avoir ≥ 2 pages vierges.",
        s: "<b>Photocopier TOUTES les pages non vierges :</b> page photo/bio, page validité, TOUTES les pages avec tampons, cachets ou visas.<br><b>Faire 2 jeux complets</b> — CAPAGO garde les copies, te rend les originaux.",
        print: "📄 ORIGINAL + photocopies N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "civ2",
        t: "2 photos d'identité aux normes OACI",
        d: "35×45 mm, fond blanc strict, visage centré, expression neutre, yeux ouverts, moins de 3 mois.",
        s: '<b>Où :</b> studio photo professionnel à M\'Sila ou Constantine. Demander explicitement "photos OACI pour visa France".<br><b>Éviter :</b> selfie, fond coloré, lunettes.',
        print: "📸 PHOTOS physiques studio uniquement — pas d'impression maison.",
        g: ["req"],
      },
      {
        id: "civ3",
        t: "Acte de naissance avec filiation — original + traduction si arabe",
        d: "Extrait mentionnant tes prénom/nom, date/lieu de naissance, ET les prénoms/noms de tes deux parents.",
        s: "<b>Où obtenir :</b> bureau d'état civil de l'APC de ta commune de NAISSANCE.<br><b>Demander :</b> \"extrait d'acte de naissance avec filiation\" pour une démarche à l'étranger.<br><b>Si en arabe :</b> traducteur assermenté arabe→français. Délai 1–3 jours.<br><b>Copies :</b> certifier 2 copies à l'APC.",
        print: "📄 ORIGINAL papier + copie N&B (+ traduction assermentée si arabe). Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "civ4",
        t: "Fiche familiale d'état civil",
        d: "Document regroupant tous les membres de la famille. Clé pour prouver le lien fraternel avec ton frère → belle-sœur.",
        s: "<b>Où obtenir :</b> APC de ton domicile familial → service état civil → présenter le livret de famille ou les actes de naissance des parents. Gratuit. Délivré immédiatement ou sous 24–48h.",
        print: "📄 ORIGINAL papier + copie N&B. Pas d'impression couleur.",
        g: ["req"],
      },
    ],
  },
  {
    id: "fin",
    ico: "💰",
    bg: "#faf5ff",
    nm: "Ressources financières personnelles — CCP + Salaire",
    badge: { t: "2 mois seulement", c: "b-amb" },
    note: {
      t: "<b>Situation :</b> 2 mois de travail, compte CCP. Le CCP (Compte Courant Postal algérien) est un compte officiel parfaitement reconnu par le consulat. Tu auras au mieux 2 bulletins et 2 relevés. <b>Stratégie :</b> présente tout ce que tu as + explique dans la lettre explicative + compense avec les garants.",
      c: "n-amb",
    },
    items: [
      {
        id: "fin1",
        t: "Attestation de travail — demandée à ton employeur",
        d: "Lettre officielle sur papier en-tête confirmant ta situation professionnelle actuelle.",
        s: "<b>Quoi demander :</b> attestation mentionnant ton nom complet, intitulé du poste, date de prise de fonction, salaire mensuel brut + signature du responsable RH ou directeur + cachet.<br><b>Délai :</b> demander AUJOURD'HUI. La plupart des employeurs fournissent ça en 24–48h.",
        print: "📄 ORIGINAL papier en-tête employeur + copie N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "fin2",
        t: "Bulletins de salaire (1–2 mois disponibles)",
        d: "Présenter TOUS tes bulletins existants. Le consulat voit que l'emploi est récent.",
        s: "<b>Tes bulletins papier :</b> photocopier + garder les originaux.<br><b>Important :</b> le salaire sur le bulletin doit correspondre aux virements visibles sur le relevé CCP.",
        print: "📄 ORIGINAUX papier + photocopies N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "fin3",
        t: "Relevés de compte CCP — tous mois disponibles",
        d: "Tes relevés du compte courant postal. Même 1–2 mois sont utiles.",
        s: '<b>OPTION 1 — En agence Algérie Poste :</b> Se présenter au bureau de poste → demander "relevé de compte mensuel imprimé".<br><b>OPTION 2 — BaridiWeb :</b> <a href="https://www.baridibank.dz" target="_blank">baridibank.dz</a> → connexion → historique → exporter PDF.<br><b>Ce qui doit apparaître :</b> ton nom, numéro CCP, les virements de salaire entrants.',
        print: "📄 ORIGINAL papier (poste) ou 🖨️ COULEUR ×1 + N&B ×1 si PDF BaridiWeb.",
        g: ["req"],
      },
      {
        id: "fin4",
        t: "CV complet — obligatoire pour reprise d'études",
        d: "Exigé réglementairement quand on reprend des études après avoir travaillé. Doit expliquer toute la chronologie.",
        s: "<b>Format :</b> A4, 1–2 pages, en FRANÇAIS. Chronologique inversé (plus récent en premier).<br><b>Période entre diplôme et emploi actuel :</b> indiquer clairement \"2022–2024 : Recherche scientifique indépendante — rédaction et publication de 2 articles scientifiques + développement du business plan d'une startup issue du projet de fin d'études\".<br><b>Ne pas laisser de trou non expliqué.</b>",
        print: "🖨️ N&B ×1 — Document que tu crées toi-même.",
        g: ["req"],
      },
      {
        id: "fin5",
        t: "Capture exonération partielle CVEC",
        d: "Preuve que tu bénéficies de l'exonération partielle de la CVEC. À capturer depuis le portail étudiant.",
        s: '<b>Où obtenir :</b> <a href="https://cvec.etudiant.gouv.fr" target="_blank">cvec.etudiant.gouv.fr</a> → connecte-toi avec ton INE → si exonération partielle accordée, faire une capture d\'écran de la page de confirmation.<br><b>Pourquoi :</b> réduit le montant à payer lors de l\'inscription à l\'université. La capture sert de justificatif auprès du service des inscriptions.',
        print: "🖨️ COULEUR ×1 + N&B ×1 — Capture d'écran du portail CVEC.",
        g: ["req"],
      },
    ],
  },
  {
    id: "gfr",
    ico: "🗼",
    bg: "#f0fdf4",
    nm: "Garant France — Belle-sœur à Paris",
    badge: { t: "Pièce principale", c: "b-grn" },
    note: {
      t: "<b>Ton garant principal.</b> Elle doit prouver ≥ 615€/mois de ressources. Elle compense ton travail de 2 mois. L'attestation de prise en charge doit être légalisée à la mairie de Paris (gratuit, RDV sur paris.fr) ou chez un notaire.",
      c: "n-grn",
    },
    items: [
      {
        id: "gf1",
        t: "Attestation de prise en charge (PEC) — belle-sœur",
        d: "Document dans lequel elle s'engage officiellement à subvenir à tes besoins pendant ton séjour.",
        s: '<b>Modèle :</b> voir onglet "Lettres" → Lettre 5.<br><b>Comment légaliser :</b><br>1. Belle-sœur rédige + imprime + signe<br>2. Elle se rend à la mairie de son arrondissement parisien (paris.fr → RDV → état civil → légalisation de signature)<br>3. Présente : CNI + la lettre signée → agent appose cachet + signature. Gratuit.<br><b>Alternative :</b> notaire de quartier (≈ 20€, pas de RDV).<br><b>Délai :</b> lui demander de le faire CETTE SEMAINE.',
        print: "📄 ORIGINAL légalisé mairie Paris + copie N&B — Elle t'envoie l'original par DHL.",
        g: ["req"],
      },
      {
        id: "gf2",
        t: "3 derniers bulletins de salaire de la belle-sœur",
        d: "Mars, avril, mai 2025. Salaire net ≥ 615€/mois visible.",
        s: "<b>Elle les récupère :</b> via son espace RH/paie en ligne (Workday, PayFit, etc.) ou bulletins papier.<br><b>Transmission :</b> scan haute résolution → WhatsApp → tu imprimes.",
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDFs WhatsApp.",
        g: ["req"],
      },
      {
        id: "gf3",
        t: "3 derniers relevés bancaires de la belle-sœur",
        d: "Son compte personnel à Paris. Virements de salaire visibles chaque mois.",
        s: "<b>Elle télécharge :</b> depuis son espace bancaire en ligne → relevés PDF → t'envoie par WhatsApp.<br><b>Vérifier :</b> virements de salaire visibles et cohérents avec les bulletins.",
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDFs WhatsApp.",
        g: ["req"],
      },
      {
        id: "gf4",
        t: "Pièce d'identité de la belle-sœur (recto-verso)",
        d: "CNI française, passeport ou titre de séjour en cours de validité.",
        s: "<b>Copie recto-verso lisible.</b> Si titre de séjour : vérifier validité couvre 2025–2026.",
        print: "🖨️ COULEUR ×1 + N&B ×1 — Scan WhatsApp.",
        g: ["req"],
      },
      {
        id: "gf5",
        t: "Justificatif de domicile Paris (moins de 3 mois)",
        d: "Prouve qu'elle habite bien à Paris.",
        s: "<b>Documents acceptés :</b> facture EDF, GDF, eau (Eau de Paris), téléphonie fixe, ou avis d'imposition 2024. Moins de 3 mois.<br><b>Si en colocation :</b> attestation hébergement signée par titulaire du bail + copie facture + copie CNI du titulaire.",
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDF WhatsApp.",
        g: ["req"],
      },
      {
        id: "gf6",
        t: "Avis d'imposition 2024 de la belle-sœur",
        d: "Confirme les revenus annuels déclarés à l'administration fiscale française.",
        s: '<b>Comment l\'obtenir :</b> <a href="https://impots.gouv.fr" target="_blank">impots.gouv.fr</a> → Espace personnel → "Consulter mes documents fiscaux" → "Avis d\'imposition 2024 sur revenus 2023" → PDF.',
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDF impots.gouv.fr.",
        g: ["req"],
      },
      {
        id: "gf9",
        t: "Compte épargne de la belle-sœur",
        d: "Justificatif du compte épargne (livret A, LEP, LDD ou autre). Renforce la solidité financière du garant.",
        s: "<b>Elle télécharge :</b> depuis son espace bancaire en ligne → relevé ou attestation de solde du compte épargne → t'envoie par WhatsApp.<br><b>Ce qui doit apparaître :</b> son nom, type de compte, solde visible.",
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDF WhatsApp.",
        g: ["req"],
      },
      {
        id: "gf7",
        t: "Justificatif du lien de parenté — chaîne documentaire",
        d: "Prouver que la belle-sœur est bien l'épouse de ton frère, et que c'est bien ton frère.",
        s: "<b>Chaîne en 3 documents :</b><br>① Ton acte de naissance avec filiation (nom de tes parents)<br>② Acte de naissance de ton frère (mêmes parents = lien fraternel prouvé)<br>③ Acte de mariage du frère (nomme la belle-sœur = lien conjugal prouvé)<br><br>→ La fiche familiale d'état civil peut remplacer ①+②.<br><b>Si actes en arabe :</b> traduction assermentée.",
        print: "📄 ORIGINAUX papier + photocopies N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "gf8",
        t: "Acte de mariage du frère",
        d: "Confirme que la belle-sœur est légalement l'épouse de ton frère.",
        s: "<b>Si mariage en Algérie :</b> APC de la commune du mariage → service état civil → \"extrait d'acte de mariage\".<br><b>Si en arabe :</b> traduction assermentée requise.<br><b>Copie certifiée :</b> à l'APC.",
        print: "📄 ORIGINAL papier + copie N&B (+ traduction si arabe). Pas d'impression couleur.",
        g: ["req"],
      },
    ],
  },
  {
    id: "gdz",
    ico: "🌙",
    bg: "#fff7ed",
    nm: "Garant Algérie — Parent retraité (60 000 DA/mois)",
    badge: { t: "Fortement recommandé", c: "b-blu" },
    note: {
      t: "<b>60 000 DA ≈ 415€/mois.</b> Avec la belle-sœur à Paris (≥ 615€), tu couvres largement les 615€ requis au total. Ajouter ce garant DZ montre deux filets de sécurité — dossier très solide pour compenser les 2 mois de travail seulement.",
      c: "n-blu",
    },
    items: [
      {
        id: "gd1",
        t: "Attestation de prise en charge — parent retraité",
        d: "Le parent s'engage à contribuer financièrement à tes études.",
        s: '<b>Modèle :</b> voir onglet "Lettres" → Lettre 4.<br><b>Légaliser :</b> APC (mairie algérienne) du domicile du parent → service légalisation → original + copie + CNI du parent → cachet + signature. Timbre fiscal 200 DA.',
        print: "📄 ORIGINAL légalisé APC + copie N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "gd2",
        t: "Attestation de pension de retraite (CNAS / CNR)",
        d: "Document officiel attestant le montant mensuel exact de la retraite.",
        s: '<b>Où obtenir :</b> bureau CNAS ou CNR du lieu de résidence du parent. Se présenter avec sa CNI. Demander "attestation de pension" ou "attestation de droits". Gratuit. Délai : immédiat à 48h.',
        print: "📄 ORIGINAL papier CNAS/CNR + copie N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "gd3",
        t: "Relevés CCP du parent (3 mois)",
        d: "Montrent les virements de pension réguliers.",
        s: "Même procédure que pour toi : bureau Algérie Poste ou BaridiWeb. Vérifier que les virements mensuels CNAS/CNR sont bien visibles chaque mois.",
        print: "📄 ORIGINAL papier (poste) ou 🖨️ COULEUR ×1 + N&B ×1 si PDF BaridiWeb.",
        g: ["req"],
      },
      {
        id: "gd4",
        t: "Attestation d'affiliation CNAS",
        d: "Prouve que le parent est affilié à la CNAS et bénéficie de la couverture sociale.",
        s: "À demander auprès de l'agence CNAS du parent. Vérifier que le nom, le numéro d'affiliation et la date de validité apparaissent clairement.",
        print: "📄 ORIGINAL papier CNAS + copie N&B. Pas d'impression couleur.",
        g: ["req"],
      },
      {
        id: "gd5",
        t: "CNI du parent garant",
        d: "Pièce d'identité en cours de validité.",
        s: "Copie recto-verso lisible. Vérifier la date d'expiration.",
        print: "📄 ORIGINAL + copie N&B recto-verso. Pas d'impression couleur.",
        g: ["req"],
      },
    ],
  },
  {
    id: "lgt",
    ico: "🏨",
    bg: "#eff6ff",
    nm: "Justificatif d'hébergement",
    badge: { t: "Hôtel réservé ✓", c: "b-grn" },
    note: {
      t: "<b>CROUS :</b> la phase complémentaire ouvre le 7 juillet — impossible avant ton RDV visa du 8 juin. Ce n'est PAS un problème. La réservation hôtel + lettre explicative est parfaitement acceptée par le consulat.",
      c: "n-grn",
    },
    items: [
      {
        id: "lgt1",
        t: "Confirmation de réservation hôtel Besançon (Agoda) ✓",
        d: "Déjà réservé. À imprimer pour le dossier.",
        s: "<b>Imprimer la confirmation Agoda :</b> vérifier que la confirmation mentionne : ton nom complet, nom de l'hôtel, adresse à Besançon (25000), dates d'arrivée et départ. Si annulable, garde-la telle quelle — une réservation annulable est parfaitement valide pour le consulat.",
        print: "🖨️ COULEUR ×1 + N&B ×1 — PDF email Agoda.",
        g: ["don"],
      },
      {
        id: "lgt2",
        t: "Distance hôtel → Université sur Google Maps",
        d: "Montre que le logement est proche ou accessible depuis l'université.",
        s: "<b>Ouvrir Google Maps :</b> rechercher l'hôtel puis l'université (UFR Sciences et techniques, Besançon). Afficher l'itinéraire en transport ou à pied → capture d'écran claire : nom hôtel, nom université, distance/temps. Imprimer ou enregistrer en PDF.",
        print: "🖨️ N&B ×1 — Capture d'écran ou PDF.",
        g: ["req"],
      },
      {
        id: "lgt3",
        t: "Plan de logement mentionné dans la lettre explicative",
        d: "Le consulat veut un plan d'hébergement crédible, pas forcément un bail signé.",
        s: "Dans ta lettre : \"Hôtel réservé à Besançon pour l'arrivée. Demande CROUS dès le 7 juillet 2025. Recherche résidences étudiantes privées et colocations. Contact service logement de l'Université dès l'arrivée.\"",
        print: "🖨️ N&B ×1 — Fait partie de ta lettre explicative.",
        g: ["req"],
      },
    ],
  },
  {
    id: "letters",
    ico: "✉️",
    bg: "#fdf2f8",
    nm: "Lettres — À rédiger et joindre au dossier",
    badge: { t: "7 lettres", c: "b-pur" },
    note: {
      t: "<b>Ces lettres sont rédigées par toi (ou le garant concerné).</b> Elles complètent et expliquent les documents justificatifs. Chaque lettre doit être signée à la main. N&B ×1 sauf la lettre de prise en charge belle-sœur qui doit être légalisée.",
      c: "n-pur",
    },
    items: [
      {
        id: "let1",
        t: "Lettre de motivation",
        d: "Explique pourquoi tu veux faire ce M2 en France, ton projet professionnel, et le lien avec ton parcours.",
        s: "<b>Contenu :</b> parcours académique → motivation pour le M2 Systèmes Logiciels → projet professionnel en Algérie après les études → pourquoi Besançon / UFC.<br><b>Longueur :</b> 1 page A4 maximum.<br><b>Langue :</b> français.",
        print: "🖨️ N&B ×1 — Rédigée et signée par toi.",
        g: ["req"],
      },
      {
        id: "let2",
        t: "Lettre d'hébergement",
        d: "Explique ta situation de logement à l'arrivée et ton plan pour trouver un logement stable.",
        s: "<b>Contenu :</b> hôtel réservé à Besançon pour l'arrivée → demande CROUS dès le 7 juillet → recherche résidences privées et colocations → contact service logement université à l'arrivée.<br><b>Longueur :</b> 1 page A4 maximum.",
        print: "🖨️ N&B ×1 — Rédigée et signée par toi.",
        g: ["req"],
      },
      {
        id: "let3",
        t: "Lettre ressources financières",
        d: "Explique ta situation financière : emploi récent, soutien des garants, et capacité à financer les études.",
        s: "<b>Contenu :</b> emploi actuel (2 mois) + salaire → soutien de la belle-sœur à Paris (garant principal, ≥ 615€/mois) → soutien du père retraité en Algérie (60 000 DA/mois) → engagement à ne pas travailler illégalement.<br><b>Longueur :</b> 1 page A4 maximum.",
        print: "🖨️ N&B ×1 — Rédigée et signée par toi.",
        g: ["req"],
      },
      {
        id: "let4",
        t: "Lettre d'engagement du père",
        d: "Le père s'engage par écrit à soutenir financièrement les études en France.",
        s: "<b>Contenu :</b> identité du père → lien de parenté → montant de la pension (60 000 DA/mois) → engagement à contribuer aux frais de vie et d'études → signature manuscrite du père.<br><b>Légaliser :</b> APC du domicile du père → service légalisation → tampon + signature. Timbre fiscal 200 DA.",
        print: "📄 ORIGINAL légalisé APC + copie N&B.",
        g: ["req"],
      },
      {
        id: "let5",
        t: "Lettre prise en charge belle-sœur",
        d: "La belle-sœur s'engage officiellement à subvenir à tes besoins financiers pendant ton séjour.",
        s: "<b>Contenu :</b> identité belle-sœur → lien avec toi → engagement à couvrir les frais de vie (loyer, nourriture, transport) → montant estimé → durée (1 an).<br><b>Légaliser :</b> mairie de son arrondissement parisien (paris.fr → RDV → état civil → légalisation de signature). Gratuit. Alternative : notaire (≈ 20€).",
        print: "📄 ORIGINAL légalisé mairie Paris + copie N&B — Elle t'envoie l'original par DHL.",
        g: ["req"],
      },
      {
        id: "let6",
        t: "Lettre lien de parenté — père",
        d: "Explique et certifie le lien de parenté entre toi et ton père garant.",
        s: "<b>Contenu :</b> ton identité → identité du père → déclaration du lien père-fils/fille → référence aux documents joints (fiche familiale, acte de naissance).<br><b>Longueur :</b> 1/2 page A4.<br><b>Signataire :</b> toi (ou le père).",
        print: "🖨️ N&B ×1 — Rédigée et signée.",
        g: ["req"],
      },
      {
        id: "let7",
        t: "Lettre lien de parenté — belle-sœur",
        d: "Explique et certifie le lien entre toi et ta belle-sœur garante.",
        s: "<b>Contenu :</b> ton identité → identité du frère → identité belle-sœur → chaîne : toi → frère (même parents, voir fiche familiale) → belle-sœur (épouse du frère, voir acte de mariage).<br><b>Longueur :</b> 1/2 page A4.<br><b>Signataire :</b> toi.",
        print: "🖨️ N&B ×1 — Rédigée et signée par toi.",
        g: ["req"],
      },
    ],
  },
  {
    id: "rdv",
    ico: "📋",
    bg: "#fff1f2",
    nm: "RDV CAPAGO 8 juin — Préparation jour J",
    badge: { t: "8 juin 2025", c: "b-red" },
    note: {
      t: "<b>M'Sila → circonscription consulaire d'Annaba.</b> Centre CAPAGO : Annaba ou Constantine. Vérifier lequel est mentionné sur ta convocation. Frais payés en espèces DZD uniquement.",
      c: "n-red",
    },
    items: [
      {
        id: "rdv1",
        t: "Organiser le dossier dans un classeur — originaux + copies",
        d: "CAPAGO prend les copies. Tu gardes les originaux. Chaque document en double.",
        s: "<b>Ordre recommandé :</b><br>1. Message fin de procédure Campus France<br>2. Formulaire France-Visas signé<br>3. Attestation d'admission M2<br>4. Passeport + copies<br>5. 2 photos identité<br>6. Acte de naissance + traduction<br>7. Fiche familiale état civil<br>8. Diplôme original + copies certifiées<br>9. Relevés de notes<br>10. Attestation emploi + bulletins de salaire<br>11. Relevés CCP + capture exonération CVEC<br>12. CV<br>13. Garant France : PEC + 3 bulletins + 3 relevés + CNI + justif. domicile + avis imposition + compte épargne + lien parenté<br>14. Garant DZ : PEC + pension + relevés CCP + CNAS + CNI<br>15. Réservation hôtel + Google Maps<br>16. Lettres (7 lettres)<br>17. Lettre explicative",
        g: ["req"],
      },
      {
        id: "rdv2",
        t: "Confirmer ta circonscription consulaire",
        d: "M'Sila → Annaba → confirmer sur la convocation CAPAGO.",
        s: 'Vérifier sur <a href="https://fr-dz.capago.eu/rendezvous" target="_blank">fr-dz.capago.eu</a> que M\'Sila est sous Annaba. Le centre CAPAGO de Constantine peut aussi être compétent — vérifie ta convocation.',
        g: ["req"],
      },
      {
        id: "rdv3",
        t: "Prévoir les frais en espèces DZD",
        d: "Frais consulaires + frais CAPAGO. Espèces DZD uniquement.",
        s: "<b>Frais consulaires visa étudiant :</b> 50€ équivalent DZD au taux chancellerie du jour (≈ 7 000–8 000 DZD).<br><b>Frais service CAPAGO :</b> 29€ équivalent DZD (≈ 4 000 DZD).<br><b>Total estimé :</b> 11 000–13 000 DZD. Prévoir un peu plus.",
        g: ["req"],
      },
      {
        id: "rdv4",
        t: "Données biométriques — empreintes + photo sur place",
        d: "Prise en charge sur place par CAPAGO. Obligatoire.",
        s: "Se présenter les mains propres et sèches (éviter crème hydratante le matin). Tenue correcte pour la photo. L'agent guide toute la procédure.",
        g: ["req"],
      },
    ],
  },
];

export const AFTER_SECS = [
  {
    id: "vlsts",
    ico: "🌐",
    bg: "#eff6ff",
    nm: "Validation VLS-TS — Dans les 3 mois après arrivée",
    badge: { t: "OBLIGATOIRE dans 3 mois", c: "b-red" },
    note: {
      t: "Si tu ne valides pas ton VLS-TS dans les 3 mois après l'arrivée, tu es en situation irrégulière. C'est une démarche en ligne rapide.",
      c: "n-red",
    },
    items: [
      {
        id: "a1",
        t: "Valider le VLS-TS sur le portail ANEF",
        d: "Démarche en ligne obligatoire dès l'arrivée en France (dans les 3 mois max).",
        s: '<b>1. Aller sur :</b> <a href="https://administration-etrangers-en-france.interieur.gouv.fr" target="_blank">administration-etrangers-en-france.interieur.gouv.fr</a><br><b>2. Créer un compte</b> avec ton email<br><b>3. Saisir</b> les informations de ton visa<br><b>4. Justificatif de domicile en France</b> (adresse hôtel au début)<br><b>5. Payer</b> taxe ≈ 50€ (carte bancaire ou timbre fiscal en bureau de tabac)<br><b>6. Conserver</b> l\'attestation de validation',
        g: ["req", "Dès arrivée"],
      },
    ],
  },
  {
    id: "cvec",
    ico: "💳",
    bg: "#f0fdf4",
    nm: "CVEC — Avant l'inscription universitaire",
    badge: { t: "~103€ obligatoire", c: "b-amb" },
    items: [
      {
        id: "a2",
        t: "Payer la Contribution Vie Étudiante et de Campus",
        d: "Obligatoire avant toute inscription à l'université. Si boursier CROUS : exonération totale.",
        s: '<b>1. Aller sur :</b> <a href="https://cvec.etudiant.gouv.fr" target="_blank">cvec.etudiant.gouv.fr</a><br><b>2. Créer un compte</b> avec ton INE (fourni par l\'université)<br><b>3. Payer</b> en ligne par carte bancaire (≈ 103€)<br><b>4. Télécharger l\'attestation CVEC</b> → présenter au service des inscriptions',
        g: ["req", "Avant inscription"],
      },
    ],
  },
  {
    id: "crous",
    ico: "🏠",
    bg: "#f5f3ff",
    nm: "CROUS Besançon — Demande de logement (7 juillet)",
    badge: { t: "7 juillet 2025", c: "b-pur" },
    note: {
      t: "<b>Phase complémentaire :</b> ouverte à TOUS les étudiants (y compris internationaux sans DSE) à partir du 7 juillet. Aucun DSE requis. Les places se remplissent vite — connecte-toi le 7 juillet matin.",
      c: "n-pur",
    },
    items: [
      {
        id: "a3",
        t: "Créer ton compte MesServices.etudiant.gouv.fr (dès maintenant)",
        d: "Plateforme nationale pour logement, bourse, et toutes démarches étudiantes.",
        s: '<b>Maintenant :</b> <a href="https://messervices.etudiant.gouv.fr" target="_blank">messervices.etudiant.gouv.fr</a> → créer un compte avec ton email. Avoir le compte prêt accélère la démarche le 7 juillet.',
        g: ["req", "Maintenant"],
      },
      {
        id: "a4",
        t: "Le 7 juillet — se connecter sur trouverunlogement.lescrous.fr",
        d: "Phase complémentaire ouverte à tous. Filtrer par ville : Besançon, CROUS Bourgogne-Franche-Comté.",
        s: '<b>7 juillet matin :</b> <a href="https://trouverunlogement.lescrous.fr" target="_blank">trouverunlogement.lescrous.fr</a><br>→ Ville : Besançon | Type : chambre individuelle ou studio<br>→ Résidence Planoise (4 Place de l\'Europe, 25000 Besançon) : à partir de 340€/mois CC<br><b>Faire jusqu\'à 10 vœux</b> pour maximiser les chances.',
        g: ["req", "7 juillet"],
      },
      {
        id: "a5",
        t: "Documents à préparer pour la candidature CROUS",
        d: "À avoir prêts pour confirmer rapidement si une proposition est faite.",
        s: "<b>Documents demandés à l'entrée :</b><br>- Passeport + visa<br>- Attestation d'inscription universitaire (Besançon)<br>- RIB d'un compte bancaire FRANÇAIS<br>- Justificatif de ressources ou attestation garant<br>- <b>Assurance habitation obligatoire</b> (Maif Étudiant, Luko — en ligne en 10 min)",
        g: ["req"],
      },
      {
        id: "a6",
        t: "Alternative si CROUS complet — logements privés",
        d: "Options de repli si aucune chambre CROUS n'est disponible à Besançon.",
        s: '→ <a href="https://www.lokaviz.fr" target="_blank">lokaviz.fr</a> : annonces particuliers via CROUS<br>→ Le Bon Coin → "location meublé Besançon" (250–500€/mois studios)<br>→ <a href="https://www.appartager.com" target="_blank">appartager.com</a> : colocation Besançon<br>→ Résidences privées : Arpej, Nexity Studéa Besançon<br>→ Facebook : "Logement étudiant Besançon", "Étudiants UFC Besançon"',
        g: ["inf"],
      },
    ],
  },
  {
    id: "france",
    ico: "🏦",
    bg: "#fff7ed",
    nm: "Compte bancaire + CAF + Sécu + Carte de séjour",
    badge: { t: "Dès l'arrivée", c: "b-amb" },
    items: [
      {
        id: "a7",
        t: "Ouvrir un compte bancaire en France",
        d: "Nécessaire pour : payer le loyer, recevoir la CAF, être payé si tu travailles.",
        s: "<b>Options faciles pour étudiant étranger :</b><br>→ <b>La Banque Postale :</b> bureau de poste, accessible avec passeport + visa<br>→ <b>Boursorama / Revolut / Nickel :</b> 100% en ligne, avec passeport + selfie<br>→ <b>BNP / Société Générale :</b> en agence avec visa étudiant + justif. domicile + attestation inscription",
        g: ["req", "Dès arrivée"],
      },
      {
        id: "a8",
        t: "CAF — Aide Personnalisée au Logement (APL)",
        d: "100 à 300€/mois d'aide selon logement. Accessible avec visa étudiant valide.",
        s: '<b>Après avoir signé un bail :</b><br>1. <a href="https://www.caf.fr" target="_blank">caf.fr</a> → Créer un compte → Demander les APL<br>2. Joindre : RIB français, bail signé, passeport, visa, attestation inscription<br><b>Délai :</b> 1–2 mois pour le premier versement. Rétroactif dès le dépôt.',
        g: ["req", "Après bail signé"],
      },
      {
        id: "a9",
        t: "Sécurité Sociale étudiante (CPAM)",
        d: "Gratuite et obligatoire pour étudiants étrangers non-européens. Remplace l'assurance privée.",
        s: '<b>Lors de l\'inscription universitaire :</b> l\'université guidera vers la procédure CPAM. Ou directement :<br><a href="https://www.ameli.fr" target="_blank">ameli.fr</a> → "Étudiant étranger" → s\'affilier.<br><b>Documents :</b> passeport, visa, attestation inscription, justificatif domicile France.<br><b>Délai :</b> 2–4 semaines pour la carte Vitale.',
        g: ["req", "À l'inscription"],
      },
      {
        id: "a10",
        t: "Carte de séjour — Préfecture du Doubs (spécifique Algériens)",
        d: "En tant qu'Algérien, tu dois demander une carte de séjour à la préfecture (accord 1968).",
        s: '<b>Où :</b> Préfecture du Doubs, 8–10 rue Charles Nodier, 25000 Besançon.<br><b>RDV en ligne :</b> doubs.gouv.fr → "Titre de séjour" → prendre RDV.<br><b>Documents :</b> passeport + visa + justificatif domicile Besançon + attestation inscription + photos identité.<br><b>Faire cette démarche dans les 2 premiers mois après l\'arrivée.</b>',
        g: ["req", "Premiers mois"],
      },
    ],
  },
];
